const SOCKET_CONNECTION_INIT = "SOCKET_CONNECTION_INIT";
const SOCKET_CONNECTION_SUCCESS = "SOCKET_CONNECTION_SUCCESS";
const SOCKET_CONNECTION_ERROR = "SOCKET_CONNECTION_ERROR";
const SOCKET_CONNECTION_CLOSED = "SOCKET_CONNECTION_CLOSED";
const SOCKET_MESSAGE = "SOCKET_MESSAGE";
const SOCKET_DISCONNECT = "SOCKET_DISCONNECT";
const SOCKET_SEND = "SOCKET_SEND";

export const websocketActionTypes = {
  SOCKET_CONNECTION_INIT,
  SOCKET_CONNECTION_SUCCESS,
  SOCKET_CONNECTION_ERROR,
  SOCKET_CONNECTION_CLOSED,
  SOCKET_MESSAGE,
  SOCKET_DISCONNECT,
  SOCKET_SEND,
};
